wojciech-kulik/xcodebuild.nvim

lua/xcodebuild/actions.lua
lua/xcodebuild/project/manager.lua

Hi!
First of all, thank you for this amazing plugin. I'm having a lot of fun with it :)
I wanted to add files/directories non interactively via autocmds when creating new swift files so I added some small helper functions. Hopefully they are general enough.
However this is as far as I got, I couldn't get `list_targets` to return anything, even though it's identical to the call in `run_select_targets`. Perhaps you see something I don't? And if you like the changes we can merge them.

feat: Add list_targets and add_file_to_targets to actions

---

lua/xcodebuild/project/config.lua

fixed #58 
There is not a `.nvim` folder, and `local success, content = pcall(vim.fn.readfile, get_filepath())` got `content == 0`, `M.settings` got `0`, and crashed the process.

fix: loading settings.json fail without .nvim folder

---

lua/xcodebuild/xcode_logs/parser.lua

fix: parsing logs that contain "error:" phrase which is not error itself

---

README.md
doc/xcodebuild.txt
lua/xcodebuild/actions.lua
lua/xcodebuild/broadcasting/notifications.lua
lua/xcodebuild/core/xcode.lua
lua/xcodebuild/docs/commands.lua
lua/xcodebuild/docs/global_variables.lua
lua/xcodebuild/init.lua
lua/xcodebuild/project/builder.lua
lua/xcodebuild/project/config.lua
lua/xcodebuild/tests/runner.lua
lua/xcodebuild/ui/pickers.lua

BREAKING CHANGE: Now build configuration is detected based on the selected scheme. `XcodebuildSelectConfig`, `vim.g.xcodebuild_config`, and `actions.select_config` have been removed.
Resolves #95

fix!: handling build configurations

---

README.md
doc/xcodebuild.txt
lua/xcodebuild/docs/commands.lua
lua/xcodebuild/init.lua
lua/xcodebuild/ui/pickers.lua

User should not be able to change the project file without going through other steps.
To change the project, run wizard.

fix!: removed `XcodebuildSelectProject` command

---

doc/xcodebuild.txt
lua/xcodebuild/helpers.lua
lua/xcodebuild/tests/explorer.lua
lua/xcodebuild/xcode_logs/panel.lua

I'm currently getting the following error when trying to rebuild a project where xcodebuild isn't able to clear the logs
```
...lazy/xcodebuild.nvim/lua/xcodebuild/xcode_logs/panel.lua:246: Buffer is not 'modifiable'
stack traceback:
^I[C]: in function 'nvim_buf_set_lines'
^I...lazy/xcodebuild.nvim/lua/xcodebuild/xcode_logs/panel.lua:246: in function 'updateFoo'
^I...are/nvim/lazy/xcodebuild.nvim/lua/xcodebuild/helpers.lua:109: in function 'update_readonly_buffer'
^I...lazy/xcodebuild.nvim/lua/xcodebuild/xcode_logs/panel.lua:245: in function 'clear'
^I...azy/xcodebuild.nvim/lua/xcodebuild/xcode_logs/parser.lua:519: in function 'parse_logs'
^I.../lazy/xcodebuild.nvim/lua/xcodebuild/project/builder.lua:69: in function <.../lazy/xcodebuild.nvim/lua/xcodebuild/project/b
uilder.lua:68>
``` …

Replace uses of nvim_(buf|win)_set_option() with nvim_set_option_value()

---

doc/xcodebuild.txt
lua/xcodebuild/core/xcode.lua
lua/xcodebuild/integrations/quick.lua
specs/quick_spec.lua

When building and running, sometimes the simulator may not be on a `booted` state, and thus the script will fail without trying to boot. This applies a retry functionality to boot the simulator prior to install.

feat: boot simulator if app fails to install due to simulator state 149

---

README.md
doc/xcodebuild.txt
lua/xcodebuild/actions.lua
lua/xcodebuild/core/config.lua
lua/xcodebuild/integrations/neo-tree.lua
lua/xcodebuild/integrations/nvim-tree.lua
lua/xcodebuild/integrations/oil-nvim.lua
lua/xcodebuild/project/manager.lua

Discussed in detail here
https://github.com/wojciech-kulik/xcodebuild.nvim/discussions/152
@wojciech-kulik one question I had it where to put the option. I put it in each integration separately, but that leaves out commands like "rename current file", which do not use any of the integrations. In this PR those commands just do not use this feature, let me know if I should put this option on a global level rather than per-integration level

Added an option to automaticaly search for a non-configured project for oil, nvim-tree and neo-tree integrations

---

README.md
doc/xcodebuild.txt
lua/xcodebuild/core/config.lua
lua/xcodebuild/core/xcode.lua
lua/xcodebuild/docs/features.lua
lua/xcodebuild/docs/ios17.lua
lua/xcodebuild/docs/requirements.lua
lua/xcodebuild/health.lua
lua/xcodebuild/init.lua
lua/xcodebuild/integrations/xcodebuild-offline.lua
scripts/help-update.sh
tools/xcodebuild_offline

BREAKING CHANGE: please see `:h xcodebuild.xcodebuild-offline` to enable tool that improves build speed.
More details about this issue here (#201):
https://github.com/wojciech-kulik/xcodebuild.nvim/issues/201#issuecomment-2423828065

feat!: improved xcodebuild performance by blocking Apple domain

---

doc/xcodebuild.txt
lua/xcodebuild/core/config.lua
lua/xcodebuild/docs/features.lua
lua/xcodebuild/docs/ios17.lua
lua/xcodebuild/docs/requirements.lua
lua/xcodebuild/health.lua
lua/xcodebuild/init.lua
lua/xcodebuild/integrations/neo-tree.lua
lua/xcodebuild/integrations/nvim-tree.lua
lua/xcodebuild/integrations/oil-nvim.lua
lua/xcodebuild/integrations/remote_debugger.lua
lua/xcodebuild/integrations/xcodebuild-offline.lua
lua/xcodebuild/platform/device.lua
lua/xcodebuild/platform/device_proxy.lua
lua/xcodebuild/project/appdata.lua
lua/xcodebuild/ui/pickers.lua
tools/remote_debugger
tools/xcodebuild_offline

BREAKING CHANGE: remote debugger integration has been update to improve security. Please see `:h xcodebuild.remote-debugger-migration` to migrate your installation.

feat!: improved security of remote debugger integration (pymobiledevice3)

---

doc/xcodebuild.txt
lua/xcodebuild/actions.lua
lua/xcodebuild/core/config.lua
lua/xcodebuild/init.lua
lua/xcodebuild/integrations/neo-tree.lua
lua/xcodebuild/integrations/nvim-tree.lua
lua/xcodebuild/integrations/oil-nvim.lua
lua/xcodebuild/project/manager.lua
specs/project_manager_spec.lua

BREAKING CHANGE: `guess_target`, `find_xcodeproj`, and `should_update_project` options have been moved to `project_manager` node and now they are shared across all file managers.

feat!: file manager options have been moved to project_manager node

---

doc/xcodebuild.txt
lua/xcodebuild/core/config.lua
lua/xcodebuild/init.lua

BREAKING CHANGE: previously "objc" filetype was set for logs buffer. However, it significantly affects performance. Therefore, the filetype has been removed, but you can still set it in your config: `logs.filetype = "objc"`

feat!: removed filetype for logs buffer

---

doc/xcodebuild.txt
lua/xcodebuild/code_coverage/coverage.lua
lua/xcodebuild/core/config.lua
lua/xcodebuild/core/xcode.lua
lua/xcodebuild/docs/features.lua
lua/xcodebuild/health.lua
lua/xcodebuild/helpers.lua
lua/xcodebuild/init.lua
lua/xcodebuild/integrations/xcode-build-server.lua
lua/xcodebuild/integrations/xcodebuild-offline.lua
lua/xcodebuild/platform/device_proxy.lua
lua/xcodebuild/platform/macos.lua
lua/xcodebuild/project/builder.lua
lua/xcodebuild/project/config.lua
lua/xcodebuild/project/manager.lua
lua/xcodebuild/tests/runner.lua
lua/xcodebuild/tests/snapshots.lua
lua/xcodebuild/ui/pickers.lua
lua/xcodebuild/util.lua

BREAKING CHANGES:
- the type of `commands.extra_build_args` and `commands.extra_test_args` options has been changed to `table`
- `projectCommand` from project configuration has been removed
- all functions previously accepting `projectCommand`, now accept `projectFile`

chore!: refactored shell commands - improved escaping

---

doc/xcodebuild.txt
lua/xcodebuild/actions.lua
lua/xcodebuild/core/config.lua
lua/xcodebuild/init.lua
lua/xcodebuild/project/config.lua
lua/xcodebuild/ui/pickers.lua

Improved #223
Changes:
- device cache is invalidated when the scheme or project file changes
- added `commands.keep_device_cache` config option if you want to keep the same cache even if scheme or project file changes

feat: improved device cache

---

lua/xcodebuild/project/assets.lua
lua/xcodebuild/ui/pickers.lua

Fix issue where Quick Look previews appear behind the terminal window when running Neovim inside of a zellij session:
- Added a check for a non-null zellij pane id (either an integer or nil) to the tmux hack in asset manager and snapshot test picker.
https://github.com/wojciech-kulik/xcodebuild.nvim/issues/271

fix: zellij + quick look previews (assets and failed snapshot test previews)

---

README.md
doc/xcodebuild.txt
lua/xcodebuild/actions.lua
lua/xcodebuild/core/config.lua
lua/xcodebuild/core/previews.lua
lua/xcodebuild/docs/commands.lua
lua/xcodebuild/helpers.lua
lua/xcodebuild/init.lua

See: `:h xcodebuild.previews`
Make sure to update Swift Package `xcodebuild-nvim-preview`, minimum version: `1.0.9`
Hot reload integration: https://github.com/wojciech-kulik/xcodebuild.nvim/wiki/Tips-&-Tricks#hot-reload
Updated instruction: https://github.com/wojciech-kulik/xcodebuild.nvim/wiki/Integrations#-previews
Now commands accept the optional `hotReload` parameter:
- `XcodebuildPreviewGenerateAndShow hotReload`
- `XcodebuildPreviewGenerate hotReload`
https://github.com/user-attachments/assets/ec6c6e96-667a-40a3-a9d3-a75c9c9cf272

feat(previews): integration with hot reload (via Inject) to make previews faster

---

doc/xcodebuild.txt
lua/xcodebuild/platform/device.lua
lua/xcodebuild/platform/macos.lua

I've noticed that log messages of macOS apps don't appear in the DAP console unless the debugger is attached. To fix this, I modified the launch process to run the app's binary directly from the bundle and attach a pseudo terminal session. Based on my tests, both steps are required to capture log messages while the app is still running.  
This is my first PR to this project—feel free to suggest any changes! 👍

Route output of macOS apps to 'app_logs.log' and DAP console

---

Makefile
doc/xcodebuild.txt
lua/xcodebuild/actions.lua
lua/xcodebuild/docs/requirements.lua
lua/xcodebuild/health.lua
lua/xcodebuild/integrations/dap.lua
lua/xcodebuild/platform/device.lua
lua/xcodebuild/platform/macos.lua
lua/xcodebuild/project/builder.lua
lua/xcodebuild/ui/picker_actions.lua

Resolves #316
To see macOS app logs without debugger, install coreutils: `brew install coreutils`.
Now, macOS app always starts detached from Neovim's process.

fix(macos)!: invalid app permissions when running app without debugger

---

lua/xcodebuild/tests/provider.lua

I've noticed that some of my test classes wouldn't run because I had comments above the class definition.  
For example:  
```swift
/// This class contains tests for ...
class MyTests { ... }
```  
In this case, the plugin mistakenly detects `contains` as the class name, preventing the tests from running.  
I've updated the regex to match only `class` keywords that appear at the beginning of a line.

fix(tests): regex for detecting test class name

---

doc/xcodebuild.txt
lua/xcodebuild/core/xcode.lua
lua/xcodebuild/ui/pickers.lua

Added "[Reload Schemes]" option to fetch all schemes using xcodebuild command.
Resolves #330

fix(schemes): not showing schemes when using xcworkspace with multiple projects

---

doc/xcodebuild.txt
lua/xcodebuild/docs/ios17.lua
lua/xcodebuild/helpers.lua
lua/xcodebuild/integrations/dap.lua
lua/xcodebuild/integrations/remote_debugger.lua
lua/xcodebuild/platform/device_proxy.lua
tools/remote_debugger

BREAKING CHANGES: requires to update `remote_debugger` script, see: `:h xcodebuild.remote-debugger-update`

fix(dap)!: debbuging on real iOS 18.2+ device

---

lua/xcodebuild/project/appdata.lua

This fixes #345 
`.nvim/xcodebuild` directory is created using `util.shell` which in turn calls `vim.fn.jobstart`.
It is called with a String  as parameter, according to `:help jobstart`:
```
If {cmd} is a List it runs directly (no 'shell').
If {cmd} is a String it runs in the 'shell', like this: >vim
call jobstart(split(&shell) + split(&shellcmdflag) + ['{cmd}'])
```
As it turns out nushell has its own implementation of mkdir that doesn't support `-p` so calling `mkdir -p .nvim/xcodebuild` fails.
Replacing the call by:
`util.shell({ "mkdir", "-p", ".nvim/xcodebuild" })` makes nvim call the `mkdir` command in the path directly rather than go through the shell.

fix: start wizzard when launched from nushell
