README.md, lua/xcodebuild/config.lua, lua/xcodebuild/coordinator.lua, lua/xcodebuild/parser.lua, lua/xcodebuild/pickers.lua, lua/xcodebuild/util.lua
+ added project_search_max_depth config option
=> Fixed issue #5 - now Swift files are not indexed just after start

.github/workflows/check.yml
This is test PR to verify if CI integration works :)
=> ci: added cache + removed unnecessary steps

CONTRIBUTING.md, Makefile, README.md, doc/xcodebuild.txt, lua/xcodebuild/docs/features.lua, lua/xcodebuild/docs/ios17.lua, lua/xcodebuild/docs/requirements.lua, lua/xcodebuild/health.lua, scripts/help-update.sh
Run `:checkhealth xcodebuild` to see results
=> feat: added support for lazy.nvim checkhealth command + updated docs

lua/xcodebuild/tests/explorer.lua
=> fix: glitching Test Explorer on Neovim v0.10 (pre-release) - temporary workaround

doc/xcodebuild.txt, lua/xcodebuild/core/xcode.lua, lua/xcodebuild/project/appdata.lua, lua/xcodebuild/project/config.lua, lua/xcodebuild/tests/enumeration_parser.lua, lua/xcodebuild/util.lua, lua/xcodebuild/xcode_logs/parser.lua, specs/parser_spec.lua
=> fix: reading data from files

doc/xcodebuild.txt, lua/xcodebuild/tests/explorer.lua, lua/xcodebuild/tests/runner.lua
=> fix: showing Test Explorer when auto_open=false

lua/xcodebuild/tests/enumeration_parser.lua, lua/xcodebuild/tests/explorer.lua
=> feat: support for Quick (listing tests when only classes are provided)

doc/xcodebuild.txt, lua/xcodebuild/code_coverage/coverage.lua, lua/xcodebuild/core/constants.lua
=> fix: jumping between uncovered lines when signs are customized

doc/xcodebuild.txt, lua/xcodebuild/actions.lua, lua/xcodebuild/core/config.lua, lua/xcodebuild/init.lua, lua/xcodebuild/integrations/lsp.lua, lua/xcodebuild/integrations/xcode_build_server.lua, lua/xcodebuild/ui/pickers.lua
=> feat: enable xcode-build-server integration by default

README.md, doc/xcodebuild.txt, lua/xcodebuild/integrations/dap.lua, lua/xcodebuild/project/appdata.lua
See `:h xcodebuild.dap`
Resolves #70
=> feat: built-in configurations for nvim-dap

lua/xcodebuild/xcode_logs/parser.lua
=> fix: collecting xcodebuild logs

README.md, doc/xcodebuild.txt, lua/xcodebuild/core/config.lua, lua/xcodebuild/docs/features.lua, lua/xcodebuild/docs/requirements.lua, lua/xcodebuild/health.lua, lua/xcodebuild/init.lua, lua/xcodebuild/integrations/nvim-tree.lua, lua/xcodebuild/integrations/oil-nvim.lua, lua/xcodebuild/project/manager.lua
Integration based on: https://github.com/stevearc/oil.nvim/issues/310
=> feat: oil.nvim integration

lua/xcodebuild/tests/explorer.lua
Optimized animations and Test Explorer refreshing
=> fix: Test Explorer performance

README.md, doc/xcodebuild.txt, lua/xcodebuild/core/config.lua, lua/xcodebuild/docs/features.lua, lua/xcodebuild/docs/requirements.lua, lua/xcodebuild/health.lua, lua/xcodebuild/init.lua, lua/xcodebuild/integrations/neo-tree.lua, lua/xcodebuild/integrations/nvim-tree.lua, lua/xcodebuild/integrations/oil-nvim.lua, scripts/help-update.sh
=> feat: added integration with neo-tree.nvim

README.md, doc/xcodebuild.txt, lua/xcodebuild/core/constants.lua, lua/xcodebuild/core/xcode.lua, lua/xcodebuild/docs/features.lua, lua/xcodebuild/docs/global_variables.lua, lua/xcodebuild/docs/requirements.lua, lua/xcodebuild/init.lua, lua/xcodebuild/integrations/dap.lua, lua/xcodebuild/platform/device.lua, lua/xcodebuild/platform/device_proxy.lua, lua/xcodebuild/tests/runner.lua, lua/xcodebuild/ui/pickers.lua
=> feat: added support for watchOS, tvOS, and visionOS

lua/xcodebuild/core/xcode.lua
=> fix: reverted scheme detection based on generated files

lua/xcodebuild/helpers.lua, lua/xcodebuild/integrations/dap.lua
=> feat: automatic stopping nvim-dap session when a new action is called

doc/xcodebuild.txt, lua/xcodebuild/integrations/dap.lua, lua/xcodebuild/ui/pickers.lua
=> feat: added debug actions & sections to XcodebuildPicker

README.md, doc/xcodebuild.txt, lua/xcodebuild/core/config.lua, lua/xcodebuild/helpers.lua, lua/xcodebuild/init.lua, lua/xcodebuild/project/builder.lua, lua/xcodebuild/tests/runner.lua, lua/xcodebuild/xcode_logs/panel.lua, lua/xcodebuild/xcode_logs/parser.lua
=> feat: showing live logs in the buffer

lua/xcodebuild/integrations/lsp.lua
=> fix: issue with LSP restart

lua/xcodebuild/ui/pickers.lua, scripts/luals-check.sh
=> fix: race-condition causing infinite loading of devices

README.md, doc/xcodebuild.txt, lua/xcodebuild/core/config.lua, lua/xcodebuild/core/xcode.lua, lua/xcodebuild/init.lua
Can be disabled using `commands.focus_simulator_on_app_launch`
=> feat: focus simulator on app launch

lua/xcodebuild/xcode_logs/panel.lua
=> fix: invalid check if xcbeautify is available

lua/xcodebuild/core/autocmd.lua
=> feat: set swift filetype for *.swiftinterface buffers

lua/xcodebuild/integrations/dap.lua
=> feat: disabled C++ breakpoints added by nvim-dap

doc/xcodebuild.txt, lua/xcodebuild/actions.lua, lua/xcodebuild/tests/explorer.lua, lua/xcodebuild/tests/runner.lua
=> feat: disabled automatic test enumeration to improve performance

README.md, doc/xcodebuild.txt, lua/xcodebuild/actions.lua, lua/xcodebuild/broadcasting/notifications.lua, lua/xcodebuild/code_coverage/coverage.lua, lua/xcodebuild/core/autocmd.lua, lua/xcodebuild/core/config.lua, lua/xcodebuild/core/xcode.lua, lua/xcodebuild/helpers.lua, lua/xcodebuild/integrations/dap.lua, lua/xcodebuild/platform/device.lua, lua/xcodebuild/project/builder.lua, lua/xcodebuild/project/config.lua, lua/xcodebuild/project/manager.lua, lua/xcodebuild/tests/runner.lua, lua/xcodebuild/tests/search.lua, lua/xcodebuild/ui/picker_actions.lua, lua/xcodebuild/ui/pickers.lua, lua/xcodebuild/xcode_logs/parser.lua, scripts/help-update.sh
Resolves #127
Swift Package integration supports all currently available operations besides running and debugging as it's not possible to create iOS/macOS app using `Package.swift`
=> feat: added support for Swift Packages

doc/xcodebuild.txt, lua/xcodebuild/core/config.lua, lua/xcodebuild/init.lua, lua/xcodebuild/project/manager.lua
Resolves #199
See: `config.project_manager.project_for_path`
=> feat: config option to provide custom project path

lua/xcodebuild/tests/search.lua
=> fix: improved test suite search using LSP

lua/xcodebuild/health.lua, lua/xcodebuild/util.lua
=> fix: invalid check if `fd` tool is installed

lua/xcodebuild/tests/runner.lua
=> fix: added support to run tests without using test plan

lua/xcodebuild/ui/pickers.lua
=> fix: remaining test plan from previously selected project

README.md
=> chore: updated sponsors

lua/xcodebuild/core/xcode.lua, lua/xcodebuild/tests/diagnostics.lua, lua/xcodebuild/tests/provider.lua, lua/xcodebuild/tests/xcresult_parser.lua, lua/xcodebuild/xcode_logs/panel.lua, lua/xcodebuild/xcode_logs/parser.lua, specs/parser_spec.lua, specs/parser_test_data/tc23.log, specs/parser_test_data/tc23_out.log
=> fix: presenting incorrect results when using Swift Testing

doc/xcodebuild.txt, lua/xcodebuild/actions.lua, lua/xcodebuild/core/xcode.lua, lua/xcodebuild/docs/commands.lua, lua/xcodebuild/init.lua, lua/xcodebuild/integrations/remote_debugger.lua, lua/xcodebuild/platform/device_proxy.lua, lua/xcodebuild/platform/macos.lua, lua/xcodebuild/project/appdata.lua, lua/xcodebuild/ui/picker_actions.lua
=> feat: environment variables management (`XcodebuildEditEnvVars`)

doc/xcodebuild.txt, lua/xcodebuild/actions.lua, lua/xcodebuild/broadcasting/notifications.lua, lua/xcodebuild/code_coverage/coverage.lua, lua/xcodebuild/core/xcode.lua, lua/xcodebuild/helpers.lua, lua/xcodebuild/integrations/dap.lua, lua/xcodebuild/integrations/neo-tree.lua, lua/xcodebuild/integrations/nvim-tree.lua, lua/xcodebuild/integrations/oil-nvim.lua, lua/xcodebuild/platform/device.lua, lua/xcodebuild/project/builder.lua, lua/xcodebuild/project/config.lua, lua/xcodebuild/project/manager.lua, lua/xcodebuild/tests/runner.lua, lua/xcodebuild/tests/search.lua, lua/xcodebuild/ui/picker_actions.lua, lua/xcodebuild/ui/pickers.lua
=> feat: added static library support + custom build dir

README.md
@soundsmitten thank you for becoming a sponsor 🍻!
=> docs: updated sponsors

doc/xcodebuild.txt, lua/xcodebuild/docs/ios17.lua, lua/xcodebuild/integrations/xcodebuild-offline.lua
=> docs: updated documentation to be compatible with old macOS versions

Makefile, doc/xcodebuild.txt, lua/xcodebuild/docs/commands.lua, lua/xcodebuild/docs/requirements.lua, lua/xcodebuild/integrations/dap.lua, lua/xcodebuild/integrations/remote_debugger.lua, lua/xcodebuild/platform/device_proxy.lua
=> feat: added commands to attach/detach debugger

doc/xcodebuild.txt, lua/xcodebuild/docs/commands.lua, lua/xcodebuild/integrations/dap.lua
=> feat: added `XcodebuildDebug` and `XcodebuildBuildDebug` commands

lua/xcodebuild/tests/xcresult_parser.lua
=> fix(swift-testing): not counting skipped tests as failures

doc/xcodebuild.txt, lua/xcodebuild/core/autocmd.lua, lua/xcodebuild/core/config.lua, lua/xcodebuild/helpers.lua, lua/xcodebuild/init.lua, lua/xcodebuild/integrations/xcode-build-server.lua, lua/xcodebuild/project/config.lua, lua/xcodebuild/project/manager.lua, lua/xcodebuild/ui/pickers.lua
See: `xcodebuild.guess-scheme`
Connected with: #286
=> fix: `guess_scheme` feature + optimization + refactoring

doc/xcodebuild.txt, lua/xcodebuild/integrations/dap-symbolicate.lua, lua/xcodebuild/integrations/dap.lua, scripts/help-update.sh
=> feat(dap): added printing symbolicated crash call stack

lua/xcodebuild/integrations/dap-symbolicate.lua, lua/xcodebuild/integrations/dap.lua, lua/xcodebuild/integrations/remote_debugger.lua
=> feat(dap): printing symbolicated crashes from physical devices

doc/xcodebuild.txt, lua/xcodebuild/integrations/dap.lua
=> feat(dap): added `lldbPath` parameter to support non-default Xcode location

lua/xcodebuild/ui/pickers.lua
=> fix: sending `XcodebuildProjectSettingsUpdated` after project setup

README.md, doc/xcodebuild.txt, lua/xcodebuild/actions.lua, lua/xcodebuild/core/config.lua, lua/xcodebuild/core/previews.lua, lua/xcodebuild/docs/commands.lua, lua/xcodebuild/docs/features.lua, lua/xcodebuild/docs/keybindings.lua, lua/xcodebuild/docs/requirements.lua, lua/xcodebuild/health.lua, lua/xcodebuild/init.lua, lua/xcodebuild/project/builder.lua, lua/xcodebuild/ui/picker_actions.lua, scripts/help-update.sh
See `:h xcodebuild.previews`
https://github.com/user-attachments/assets/4e4268a6-30e9-4c4e-bfeb-f2d6fcb98b71
Learn more: https://github.com/wojciech-kulik/xcodebuild.nvim/wiki/Integrations#-previews
=> feat!: added previews for SwiftUI, UIKit, and AppKit

doc/xcodebuild.txt, lua/xcodebuild/actions.lua, lua/xcodebuild/integrations/dap.lua, lua/xcodebuild/platform/device.lua, lua/xcodebuild/platform/macos.lua, lua/xcodebuild/project/builder.lua, lua/xcodebuild/ui/picker_actions.lua
@FelixLisczyk FYI, I added extra option to the picker for macOS project to run the app detached if needed.
=> feat: added picker action to run macOS app detached

lua/xcodebuild/core/xcode.lua
=> fix(pickers): device selection when unexpected line appears

lua/xcodebuild/core/previews.lua
=> fix(previews): clearing Snacks cache before generating preview
